# Generated by Django 3.2.5 on 2021-07-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageGallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
