# Generated by Django 3.2.5 on 2021-07-12 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageGallery', '0002_alter_galleryimage_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='slug',
        ),
    ]
