# Generated by Django 3.2.5 on 2021-07-15 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageGallery', '0003_remove_galleryimage_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='tags',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imageGallery.tags'),
        ),
    ]
